create or replace directory EXPORT_DIR as 'M:/My Projects/WorkStuff/NCS 3/Database/Import_Export';
create or replace directory IMPORT_DIR as 'M:/My Projects/WorkStuff/NCS 3/Database/Import_Export';

grant read on directory IMPORT_DIR to NCS3;
grant write on directory EXPORT_DIR to NCS3;
/

CREATE USER NCS
  IDENTIFIED BY NCS
  DEFAULT TABLESPACE NCS_IMPORT
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
/

  -- 3 Roles for NCS3
GRANT AUTHENTICATEDUSER TO NCS;
GRANT CONNECT TO NCS;
GRANT DBA TO NCS;
  ALTER USER NCS DEFAULT ROLE ALL;
  -- 9 System Privileges for NCS3
GRANT CHANGE NOTIFICATION TO NCS;
GRANT SELECT ANY CUBE TO NCS;
GRANT SELECT ANY CUBE DIMENSION TO NCS;
GRANT SELECT ANY DICTIONARY TO NCS;
GRANT SELECT ANY MINING MODEL TO NCS;
GRANT SELECT ANY SEQUENCE TO NCS;
GRANT SELECT ANY TABLE TO NCS;
GRANT SELECT ANY TRANSACTION TO NCS;
GRANT UNLIMITED TABLESPACE TO NCS;
/

commit;
