/* Formatted on 1/7/2014 7:19:46 PM (QP5 v5.256.13226.35538) */
DROP TABLESPACE NCS3_STATS
/
DROP TABLESPACE NCS3_STATS_INDEX
/
DROP TABLESPACE NCS3_MESSAGES
/
DROP TABLESPACE NCS3_MESSAGES_INDEX
/
DROP TABLESPACE NCS3_LOOKUP
/
DROP TABLESPACE NCS3_LOOKUP_INDEX
/
DROP TABLESPACE NCS3_EVENTS
/
DROP TABLESPACE NCS3_EVENTS_INDEX
/
DROP TABLESPACE NCS3_TEMP
/

CREATE TEMPORARY TABLESPACE NCS3_TEMP TEMPFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_TEMP01.DBF' SIZE 1G AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_TEMP02.DBF' SIZE 1G AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_TEMP03.DBF' SIZE 1G AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_TEMP04.DBF' SIZE 1G AUTOEXTEND ON NEXT 1M MAXSIZE UNLIMITED
TABLESPACE GROUP ''
EXTENT MANAGEMENT LOCAL UNIFORM SIZE 1M
/

CREATE TABLESPACE NCS3_USER DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_USER01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_USER02.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_STATS DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_STATS01.DBF' SIZE 10G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_STATS02.DBF' SIZE 10G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_STATS_INDEX DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_STATS_INDEX01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_MESSAGES DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_MESSAGES01.DBF' SIZE 10G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_MESSAGES02.DBF' SIZE 10G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON;
/

CREATE TABLESPACE NCS3_MESSAGES_INDEX DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_MESSAGES_INDEX01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_EVENTS DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_EVENTS01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_EVENTS02.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_EVENTS_INDEX DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_EVENTS_INDEX01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_LOOKUP DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_LOOKUP01.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED,
  'D:\APP\ORACLE\oradata\orcl\NCS3_LOOKUP02.DBF' SIZE 5G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

CREATE TABLESPACE NCS3_LOOKUP_INDEX DATAFILE
  'D:\APP\ORACLE\oradata\orcl\NCS3_LOOKUP_INDEX01.DBF' SIZE 2G AUTOEXTEND ON NEXT 10M MAXSIZE UNLIMITED
LOGGING
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT AUTO
FLASHBACK ON
/

DROP USER NCS3 CASCADE
/


CREATE USER NCS3
  IDENTIFIED BY NCS3
  DEFAULT TABLESPACE NCS3_USER
  TEMPORARY TABLESPACE NCS3_TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
/

  -- 3 Roles for NCS3
GRANT AUTHENTICATEDUSER TO NCS3;
GRANT CONNECT TO NCS3;
GRANT DBA TO NCS3;
  ALTER USER NCS3 DEFAULT ROLE ALL;
  -- 9 System Privileges for NCS3
GRANT CHANGE NOTIFICATION TO NCS3;
GRANT SELECT ANY CUBE TO NCS3;
GRANT SELECT ANY CUBE DIMENSION TO NCS3;
GRANT SELECT ANY DICTIONARY TO NCS3;
GRANT SELECT ANY MINING MODEL TO NCS3;
GRANT SELECT ANY SEQUENCE TO NCS3;
GRANT SELECT ANY TABLE TO NCS3;
GRANT SELECT ANY TRANSACTION TO NCS3;
GRANT UNLIMITED TABLESPACE TO NCS3;
