$PRCM,1,IMA User Name    : Hewlett-Packard Company
$PRCM,1,IMA Company Name : CyberLink
$PRCM,1,IMA CDKey        : 
$PRCM,1,IMA OS Version   : Windows 7 Home PremiumService Pack 1
$PRCM,1,IMA c:\Program Files (x86)\CyberLink\Power2Go\Power2Go.exe : Version 6.1.0.5391
$PRCM,1,IMA CBS.dll : Version 7.7.6531  

$PRCM,1,IMA ==================================================================

$PRCM,5,IMA Total physical memory : 15856MB (16237156KB)
$PRCM,5,IMA Free physical memory  : 12359MB (12655616KB)
$PRCM,5,IMA Memory load	      : 22 percent

$PRCM,5,IMA Number of CPU : 4
$PRCM,5,IMA CPU Name      : AMD A6-3600 APU with Radeon(tm) HD Graphics
$PRCM,5,IMA CPU Speed     : 2096 MHz

==================================================================

$PRCM,1,IMA 9.8.2012
$PRCM,1,IMA Task Type : Burn Disc Image

$PRCM,1,IMA 22:49:00, File(cl_DiscCopy.cpp), Line(8440)
$PRCM,1,IMA 	-> Begin burning process
$PRCM,1,IMA 	Current drive:	<F: ASUS    	BW-12B1ST       	1.03>
$PRCM,1,IMA 	====== Disc Info =======
$PRCM,38,IMA 	Disc Type: DVD-R
$PRCM,38,IMA 	Disc Status: Blank, Appendable
$PRCM,1,IMA 	Num. of Sessions: 1 	Num. of Tracks: 1
$PRCM,7,IMA 	Book Type: DVD-R
$PRCM,1,IMA 	Track Path: 
$PRCM,1,IMA 	Parallel Track Path
$PRCM,1,IMA 	Diameter Length: 120mm 	Layer Counts: 1
$PRCM,9,IMA 	Data Area Start PSN: 196608 	End PSN: 0 	End PSN on Layer 0: 0
$PRCM,1,IMA 	End PSN : 120mm 	Layer Counts: 1
$PRCM,5,IMA 	Disc Capacity: 2297888LBs
$PRCM,5,IMA 	Free Size: 2297888LBs Used Size: 0LBs
$PRCM,1,IMA 	========================
$PRCM,12,IMA 	Current writing speed(x): 4.0
$PRCM,12,IMA 	-> Burn from image

$PRCM,5,IMA 22:49:00, file(cl_DiscCopy.cpp), line(8863)
$PRCM,1,IMA 	-> Prepare writing disc
$PRCM,1,IMA 	Burn option: w/ buffer underrun protection
$PRCM,1,IMA 	Burn option: w/o simulation
$PRCM,1,IMA 	Burn option: w/o close disc
$PRCM,1,IMA 	Burn option: w/ verify disc
$PRCM,1,IMA 	Burn mode: PACKET_INC

$PRCM,25,22:53:31, file(cl_DiscCopy.cpp), line(1060)
$PRCM,1,IMA 	-> End write
$PRCM,1,IMA 	Last write LBA: 648352

$PRCM,5,IMA 22:53:35, file(cl_DiscCopy.cpp), line(1146)
$PRCM,1,IMA 	-> Close track: 1

$PRCM,5,IMA 22:54:13, file(cl_DiscCopy.cpp), line(1203)
$PRCM,1,IMA 	-> Close disc
$PRCM,1,IMA 	-> End burning process

$PRCM,1,IMA ==================================================================
