$PRCM,1,RSIM User Name    : Hewlett-Packard Company
$PRCM,1,RSIM Company Name : CyberLink
$PRCM,1,RSIM CDKey        : 
$PRCM,1,RSIM OS Version   : Windows 7 Home PremiumService Pack 1
$PRCM,1,RSIM c:\Program Files (x86)\CyberLink\Power2Go\Power2Go.exe : Version 6.1.0.5391
$PRCM,1,RSIM CBS.dll : Version 7.7.6531  

$PRCM,1,RSIM ==================================================================

$PRCM,5,RSIM Total physical memory : 15856MB (16237156KB)
$PRCM,5,RSIM Free physical memory  : 12359MB (12655616KB)
$PRCM,5,RSIM Memory load	      : 22 percent

$PRCM,5,RSIM Number of CPU : 4
$PRCM,5,RSIM CPU Name      : AMD A6-3600 APU with Radeon(tm) HD Graphics
$PRCM,5,RSIM CPU Speed     : 2096 MHz

==================================================================

$PRCM,1,RSIM 9.8.2012
$PRCM,1,RSIM Task Type : Burn Disc Image

$PRCM,1,RSIM 22:49:00, File(cl_DiscCopy.cpp), Line(8440)
$PRCM,1,RSIM 	-> Begin burning process
$PRCM,1,RSIM 	Current drive:	<F: ASUS    	BW-12B1ST       	1.03>
$PRCM,1,RSIM 	====== Disc Info =======
$PRCM,38,RSIM 	Disc Type: DVD-R
$PRCM,38,RSIM 	Disc Status: Blank, Appendable
$PRCM,1,RSIM 	Num. of Sessions: 1 	Num. of Tracks: 1
$PRCM,7,RSIM 	Book Type: DVD-R
$PRCM,1,RSIM 	Track Path: 
$PRCM,1,RSIM 	Parallel Track Path
$PRCM,1,RSIM 	Diameter Length: 120mm 	Layer Counts: 1
$PRCM,9,RSIM 	Data Area Start PSN: 196608 	End PSN: 0 	End PSN on Layer 0: 0
$PRCM,1,RSIM 	End PSN : 120mm 	Layer Counts: 1
$PRCM,5,RSIM 	Disc Capacity: 2297888LBs
$PRCM,5,RSIM 	Free Size: 2297888LBs Used Size: 0LBs
$PRCM,1,RSIM 	========================
$PRCM,12,RSIM 	Current writing speed(x): 4.0
$PRCM,12,RSIM 	-> Burn from image

$PRCM,5,RSIM 22:49:00, file(cl_DiscCopy.cpp), line(8863)
$PRCM,1,RSIM 	-> Prepare writing disc
$PRCM,1,RSIM 	Burn option: w/ buffer underrun protection
$PRCM,1,RSIM 	Burn option: w/o simulation
$PRCM,1,RSIM 	Burn option: w/o close disc
$PRCM,1,RSIM 	Burn option: w/ verify disc
$PRCM,1,RSIM 	Burn mode: PACKET_INC

$PRCM,25,22:53:31, file(cl_DiscCopy.cpp), line(1060)
$PRCM,1,RSIM 	-> End write
$PRCM,1,RSIM 	Last write LBA: 648352

$PRCM,5,RSIM 22:53:35, file(cl_DiscCopy.cpp), line(1146)
$PRCM,1,RSIM 	-> Close track: 1

$PRCM,5,RSIM 22:54:13, file(cl_DiscCopy.cpp), line(1203)
$PRCM,1,RSIM 	-> Close disc
$PRCM,1,RSIM 	-> End burning process

$PRCM,1,RSIM ==================================================================
